---
language: python

python:
  - "2.7"

install:
  - pip install ansible

script:
  - ansible-playbook -i vagrant.box.client site.yml --syntax-check
  - ansible-playbook -i vagrant.box.server site.yml --syntax-check
