---
- name: install the supervisor
  yum: name=supervisor 
       enablerepo=epel 
       state=latest

- name: copy supervisord.conf from local to host
  copy: src=supervisor.conf 
        dest=/etc/supervisord.conf

- name: start the supervisor
  service: name=supervisord 
           state=started 
           enabled=yes
